
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIMPLICACIONEQUIVALENCIAleftDISYUNCIONleftCONJUNCIONleftNEGACIONCONJUNCION CONSTANTE DISYUNCION EQUIVALENCIA IMPLICACION NEGACION PARENTESIS_ABRE PARENTESIS_CIERRA VARIABLE\n    formula : NEGACION formula\n    \n    formula : PARENTESIS_ABRE formula PARENTESIS_CIERRA\n    \n    formula : VARIABLE\n               | CONSTANTE\n    formula :\n               | formula CONJUNCION formula\n               | formula DISYUNCION formula\n               | formula IMPLICACION formula\n               | formula EQUIVALENCIA formula'
    
_lr_action_items = {'NEGACION':([0,2,3,6,7,8,9,],[2,2,2,2,2,2,2,]),'PARENTESIS_ABRE':([0,2,3,6,7,8,9,],[3,3,3,3,3,3,3,]),'VARIABLE':([0,2,3,6,7,8,9,],[4,4,4,4,4,4,4,]),'CONSTANTE':([0,2,3,6,7,8,9,],[5,5,5,5,5,5,5,]),'CONJUNCION':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[-5,6,-5,-5,-3,-4,-5,-5,-5,-5,-1,6,-6,6,6,6,-2,]),'DISYUNCION':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[-5,7,-5,-5,-3,-4,-5,-5,-5,-5,-1,7,-6,-7,7,7,-2,]),'IMPLICACION':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[-5,8,-5,-5,-3,-4,-5,-5,-5,-5,-1,8,-6,-7,-8,-9,-2,]),'EQUIVALENCIA':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[-5,9,-5,-5,-3,-4,-5,-5,-5,-5,-1,9,-6,-7,-8,-9,-2,]),'$end':([0,1,2,4,5,6,7,8,9,10,12,13,14,15,16,],[-5,0,-5,-3,-4,-5,-5,-5,-5,-1,-6,-7,-8,-9,-2,]),'PARENTESIS_CIERRA':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[-5,-5,-3,-4,-5,-5,-5,-5,-1,16,-6,-7,-8,-9,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,2,3,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> NEGACION formula','formula',2,'p_negacion','Analizer.py',22),
  ('formula -> PARENTESIS_ABRE formula PARENTESIS_CIERRA','formula',3,'p_agrupacion','Analizer.py',30),
  ('formula -> VARIABLE','formula',1,'p_formula_valor','Analizer.py',36),
  ('formula -> CONSTANTE','formula',1,'p_formula_valor','Analizer.py',37),
  ('formula -> <empty>','formula',0,'p_formula','Analizer.py',42),
  ('formula -> formula CONJUNCION formula','formula',3,'p_formula','Analizer.py',43),
  ('formula -> formula DISYUNCION formula','formula',3,'p_formula','Analizer.py',44),
  ('formula -> formula IMPLICACION formula','formula',3,'p_formula','Analizer.py',45),
  ('formula -> formula EQUIVALENCIA formula','formula',3,'p_formula','Analizer.py',46),
]
